name: Build and Configure

on:
  workflow_dispatch:
    inputs:
      boards:
        description: 'Target board.'
        type: choice
        options:
          - all
          - sapphire-air
          - rock-4b
        default: "all"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y tree

      - name: Checkout armbian
        run: |
          df -hT ${PWD}
          git clone -q --single-branch --depth=1 --branch=main https://github.com/armbian/build.git

      - name: Copy userpatches
        run: |
          cp -rvf userpatches build/

      - name: Build B repository
        run: |
          pushd build
          ./compile.sh build BOARD=rock-4b BRANCH=current BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE=jammy
          popd
          df -hT ${PWD}

