name: Build

on:
  workflow_dispatch:
    inputs:

      board:
        description: 'Target Board'
        required: true
        type: choice
        options:
          - all
          - rockchip-sapphire
          - nanopim4v2
          - rock-4b
        default: "all"

      release:
        description: 'Release Version'
        required: true
        type: choice
        options:
          - bookworm
          - jammy
          - noble
        default: bookworm

      system:
        description: 'System Type'
        required: true
        type: choice
        options:
          - minimal
          - server
          - desktop
        default: minimal

      desktop:
        description: 'Desktop Type (only applicable if system is desktop)'
        required: false
        type: choice
        options:
          - xfce
          - cinnamon
          - gnome
          - i3-wm
        default: xfce

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y neofetch

      - name: Show host info
        run: |
          lscpu
          free -h
          df -hT ${PWD}
          neofetch

      - name: Checkout targets
        uses: actions/checkout@v4

      - name: Checkout armbian
        run: |
          git clone -q --single-branch --depth=1 --branch=main https://github.com/armbian/build.git

      - name: Copy targets
        run: |
          cp -rvf userpatches build/

      - name: Set up system type
        run: |
          if [ "${{ inputs.system }}" == "minimal" ]; then
            echo "Setting up for minimal system..."
            echo "SYSTEM_ARGS=BUILD_DESKTOP=no BUILD_MINIMAL=yes" >> $GITHUB_ENV
          elif [ "${{ inputs.system }}" == "server" ]; then
            echo "Setting up for server system..."
            echo "SYSTEM_ARGS=BUILD_DESKTOP=no BUILD_MINIMAL=no" >> $GITHUB_ENV
          elif [ "${{ inputs.system }}" == "desktop" ]; then
            echo "Setting up for desktop system..."
            echo "SYSTEM_ARGS=BUILD_DESKTOP=yes BUILD_MINIMAL=no DESKTOP_ENVIRONMENT=${{ inputs.desktop }} \
                  DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
                  DESKTOP_APPGROUPS_SELECTED='browsers chat desktop_tools editors email internet multimedia office programming remote_desktop'" >> $GITHUB_ENV
          fi

      - name: Build [ ${{ inputs.board }} ]
        run: |
          echo "SYSTEM_ARGS: ${SYSTEM_ARGS}"
          pushd build
          ./compile.sh build BOARD=${{ inputs.board }} \
          BRANCH=current \
          ${SYSTEM_ARGS} \
          KERNEL_CONFIGURE=no \
          RELEASE=${{ inputs.release }} \
          COMPRESS_OUTPUTIMAGE=sha,img,xz
          popd

      - name: Show remaining space
        run: |
          df -hT ${PWD}

      - name: Show images
        run: |
          ls -lh ${{ github.workspace }}/build/output/images
          echo "buildtime=$(date +"%Y.%m")" >> $GITHUB_ENV

      - name: Upload images
        uses: ncipollo/release-action@main
        if: success()
        with:
          tag: "${{ inputs.release }}_${{ env.buildtime }}"
          artifacts: "${{ github.workspace }}/build/output/images/*"
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### Armbian Image information
            - Default username: root
            - Default password: 1234
            - Config command: armbian-config
            - Upgrade command: armbian-upgrade
            - Install command: armbian-install
          draft: false
          prerelease: false
