name: Build

on:
  workflow_dispatch:
    inputs:
      boards:
        description: 'Target board.'
        type: choice
        options:
          - all
          - sapphire-air
          - rock-4b
        default: "all"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Show host info
        run: |
          lscpu
          free -h
          df -hT ${PWD}

      - name: Checkout targets
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y tree

      - name: Checkout armbian
        run: |
          git clone -q --single-branch --depth=1 --branch=main https://github.com/armbian/build.git

      - name: Copy targets
        run: |
          cp -rvf userpatches build/

      - name: Build
        run: |
          pushd build
          ./compile.sh build BOARD=rock-4b BRANCH=current BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no RELEASE=bookworm PREFER_DOCKER=no COMPRESS_OUTPUTIMAGE=sha,img,7z
          popd

      - name: Show disk space
        run: |
          df -hT ${PWD}

      - name: Show images
        run: |
          ls -lh build/output/images
