name: build

on:
  workflow_dispatch:
    inputs:

      board:
        description: 'Target Board'
        required: true
        type: choice
        options:
          - rockchip-sapphire
          - nanopim4v2
          - rock-4b
        default: "rockchip-sapphire"

      branch:
        description: 'Branch'
        required: true
        type: choice
        options:
          - current
          - edge
          - vendor
        default: current

      release:
        description: 'Release Version'
        required: true
        type: choice
        options:
          - bookworm
          - jammy
          - noble
        default: bookworm

      system:
        description: 'System Type'
        required: true
        type: choice
        options:
          - minimal
          - server
          - desktop
        default: minimal

      desktop:
        description: 'Desktop Type (if system is desktop)'
        required: false
        type: choice
        options:
          - xfce
          - cinnamon
          - gnome
          - i3-wm
        default: xfce

      vendor:
        description: 'Vendor'
        required: false
        type: choice
        options:
          - Armbian
          - Armbian-unofficial
        default: Armbian-unofficial

      suffix:
        description: 'Tag suffix'
        required: false
        type: choice
        options:
          - test
          - ''
        default: test

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y neofetch

      - name: Show host info
        run: |
          lscpu
          free -h
          df -hT ${PWD}
          neofetch

      - name: Checkout targets
        uses: actions/checkout@v4

      - name: Checkout armbian
        run: |
          git clone -q --single-branch --depth=1 --branch=main https://github.com/armbian/build.git

      - name: Copy targets
        run: |
          cp -rvf userpatches build/

      - name: Set up system type
        env:
          DESKTOP_APPGROUPS: "browsers chat desktop_tools editors email internet multimedia office programming remote_desktop"
        run: |
          if [ "${{ inputs.system }}" == "minimal" ]; then
            echo "Setting up for minimal system..."
            SYSTEM_ARGS="BUILD_DESKTOP=no BUILD_MINIMAL=yes"
          elif [ "${{ inputs.system }}" == "server" ]; then
            echo "Setting up for server system..."
            SYSTEM_ARGS="BUILD_DESKTOP=no BUILD_MINIMAL=no"
          elif [ "${{ inputs.system }}" == "desktop" ]; then
            echo "Setting up for desktop system..."
            SYSTEM_ARGS="BUILD_DESKTOP=yes BUILD_MINIMAL=no DESKTOP_ENVIRONMENT=${{ inputs.desktop }} \
                  DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
                  DESKTOP_APPGROUPS_SELECTED=\"${{ env.DESKTOP_APPGROUPS }}\""
          fi
          echo "BUILD_ARGS=$SYSTEM_ARGS" >> $GITHUB_ENV

          if [ "${{ inputs.suffix }}" == "test" ]; then
            echo "BUILD_TAG=_test" >> $GITHUB_ENV
          else
            echo "BUILD_TAG=" >> $GITHUB_ENV
          fi

      - name: Show environment
        run: |
          echo "env.BUILD_ARGS: ${{ env.BUILD_ARGS }}"
          echo "env.BUILD_TAG: ${{ env.BUILD_TAG }}"

      - name: Build [ ${{ inputs.board }} - ${{ inputs.release }} - ${{ inputs.branch }} - ${{ inputs.system }} ]
        run: |
          pushd build
          bash ./compile.sh build BOARD=${{ inputs.board }} \
          BRANCH=${{ inputs.branch }} \
          ${{ env.BUILD_ARGS }} \
          KERNEL_CONFIGURE=no \
          RELEASE=${{ inputs.release }} \
          COMPRESS_OUTPUTIMAGE=sha,img,xz \
          VENDOR=${{ inputs.vendor }}
          popd

      - name: Show remaining space
        run: |
          df -hT ${PWD}

      - name: Show images
        run: |
          ls -lh ${{ github.workspace }}/build/output/images
          echo "buildtime=$(date +"%Y.%m")" >> $GITHUB_ENV

      - name: Upload images
        uses: ncipollo/release-action@main
        if: success()
        with:
          tag: "${{ inputs.vendor }}_${{ inputs.release }}_${{ inputs.branch }}_${{ env.buildtime }}${{ env.BUILD_TAG }}"
          artifacts: "${{ github.workspace }}/build/output/images/*"
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### Armbian Image information
            - Default username: root
            - Default password: 1234
            - Config command: armbian-config
            - Upgrade command: armbian-upgrade
            - Install command: armbian-install
          draft: false
          prerelease: false
