name: Build

on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Target board'
        type: choice
        options:
          - all
          - sapphire-air
          - rock-4b
        default: "all"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Show host info
        run: |
          lscpu
          free -h
          df -hT ${PWD}

      - name: Checkout targets
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y tree

      - name: Checkout armbian
        run: |
          git clone -q --single-branch --depth=1 --branch=main https://github.com/armbian/build.git

      - name: Copy targets
        run: |
          cp -rvf userpatches build/

      - name: Build [ ${{ inputs.board }} ]
        run: |
          pushd build
          popd

      - name: Show remaining space
        run: |
          df -hT ${PWD}

      - name: Show images
        run: |
          ls -lh build/output/images
          pwd
          pwd -P

      - name: Upload images
        uses: ncipollo/release-action@main
        if: success()
        with:
          tag: test123
          artifacts: "${{ github.workspace }}/build/output/images/*"
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### Armbian Image information
            - Default username: root
            - Default password: 1234
            - Install command: armbian-install
            - Update command: armbian-update
            ### Armbian Image Verification
              - sha256sum
          draft: false
          prerelease: false
